CREATE DATABASE QLSV_2
ON PRIMARY
(NAME=QLSV_DATA,
FILENAME='T:\BTSQL\QLSV_DATA.MDF',
SIZE=10MB,
MAXSIZE=15MB,
FILEGROWTH=20%)
CREATE DATABASE QLBH_1
ON PRIMARY
( NAME = QLBH_DATA1,
FILENAME = 'T:\BTSQL\QLBH_DATA1.MDF',
SIZE = 10 , MAXSIZE = 50, FILEGROWTH = 15%),
(NAME = QLBH_DATA2,
FILENAME = 'T:\BTSQL\QLBH_DATA2.MDF',
SIZE = 10, MAXSIZE = 50, FILEGROWTH = 15%),
(NAME = QLBH_DATA3,
FILENAME = 'T:\BTSQL\QLBH_DATA3.NDF',
SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5),
(NAME = QLBH_DATA4,
FILENAME = 'T:\BTSQL\QLBH_DATA4.NDF',
SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5)
LOG ON
(NAME = 'QLBH_LOG',
FILENAME = 'T:\BTSQL\QLBH_LOG.LDF',
SIZE = 5MB,
MAXSIZE = 25MB,
FILEGROWTH = 5MB)
SP_HELPDB QLSV_2
ALTER DATABASE QLBH_1 
MODIFY FILE (NAME = 'QLBH_LOG', SIZE = 10MB)